#!/usr/bin/env node
/**
 * Auto-detect local IP and update .env files for network access
 * Run this before starting the dev server when on a new network
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  
  // Priority: ethernet > wifi > other
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      // Skip internal and non-IPv4 addresses
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  
  return '127.0.0.1';
}

function updateEnvFile(filePath, ip) {
  const envContent = `# Frontend Environment Variables
# Auto-generated by setup-network.js

VITE_API_BASE_URL=http://${ip}:5000/api`;

  fs.writeFileSync(filePath, envContent, 'utf8');
  console.log(`✅ Updated ${filePath} with IP: ${ip}`);
}

const ip = getLocalIP();
console.log(`🔍 Detected local IP: ${ip}`);

const webEnvPath = path.join(__dirname, 'packages/web/.env.local');
updateEnvFile(webEnvPath, ip);

console.log(`
✨ Network setup complete!

Access your app from another machine at:
👉 http://${ip}:3000

If you switch networks, run this again:
📌 npm run setup:network
`);
