import { DiseaseClinicalPlaybook } from "@medical-app/shared";

export const diseasePlaybooks: Record<string, DiseaseClinicalPlaybook> = {
  "J18.9": {
    summary: "Lower respiratory tract infection causing alveolar inflammation and gas exchange failure. Severity is driven by hypoxia, sepsis physiology, and the burden of consolidation.",
    riskFactors: ["advanced age", "smoker", "chronic lung disease", "immunocompromised state", "recent viral illness"],
    complications: ["respiratory failure", "pleural effusion", "lung abscess", "sepsis"],
    redFlags: ["oxygen saturation below 92%", "confusion", "hypotension", "respiratory distress", "multilobar disease"],
    supportiveCare: ["supplemental oxygen when hypoxic", "oral or IV hydration", "antipyretics", "early mobilization when stable"],
    monitoring: ["oxygen saturation trend", "respiratory rate", "fever curve", "hemodynamic status"],
    followUp: ["review within 48-72 hours if outpatient", "repeat chest imaging when non-resolving", "reassess antibiotic response"],
    disposition: ["outpatient if stable and low risk", "admit if hypoxic or septic", "escalate to ICU if respiratory failure develops"],
    differentialClues: ["productive cough with focal crackles favors pneumonia", "pleuritic pain with fever and infiltrate supports infection over PE"],
    vitalPatterns: [
      { metric: "temperature", expected: "fever is common", interpretation: "systemic inflammatory response", highAlert: 38 },
      { metric: "respiratoryRate", expected: "tachypnea is common", interpretation: "worsening work of breathing or poor gas exchange", highAlert: 20 },
      { metric: "oxygenSaturation", expected: "may fall with consolidation", interpretation: "hypoxia suggests more severe disease", lowAlert: 92 },
      { metric: "pulse", expected: "sinus tachycardia often accompanies fever", interpretation: "look for sepsis or dehydration", highAlert: 100 },
    ],
    investigationPlan: [
      { name: "Chest X-ray", type: "Imaging", priority: "Urgent", reason: "confirm infiltrate and extent of disease", expectedFindings: "lobar or patchy infiltrates" },
      { name: "CBC", type: "Lab", priority: "Routine", reason: "assess leukocytosis and inflammatory response", expectedFindings: "neutrophilia in bacterial infection" },
      { name: "Blood cultures", type: "Lab", priority: "Targeted", reason: "identify bacteremia in moderate to severe disease", expectedFindings: "organism isolation before antibiotics when possible" },
      { name: "Sputum culture", type: "Lab", priority: "Targeted", reason: "guide therapy in severe or non-resolving infection", expectedFindings: "causative pathogen and sensitivities" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Amoxicillin", rationale: "community-acquired pneumonia coverage for low-risk patients", dose: "500 mg", frequency: "three times daily", duration: "5-7 days", instructions: "review after 48-72 hours and escalate if deteriorating", commonSideEffects: ["diarrhea", "rash"], contraindications: ["penicillin allergy"] },
      { category: "Adjunct", medicineName: "Azithromycin", rationale: "consider when atypical coverage is needed", dose: "500 mg", frequency: "once daily", duration: "3 days", instructions: "use where atypical pneumonia is suspected", commonSideEffects: ["nausea", "QT prolongation"], contraindications: ["significant QT prolongation"] },
      { category: "Supportive", medicineName: "Ceftriaxone", rationale: "parenteral option for sicker inpatients or escalation", dose: "1-2 g", frequency: "once daily", duration: "5-7 days", instructions: "combine with local guideline-based coverage in severe disease", commonSideEffects: ["biliary sludge", "diarrhea"], contraindications: ["severe cephalosporin allergy"] },
    ],
  },
  "J45.9": {
    summary: "Reversible obstructive airway disease with exacerbations triggered by inflammation, allergens, infection, or poor controller adherence.",
    riskFactors: ["atopy", "allergen exposure", "smoker", "exercise trigger", "recent respiratory infection"],
    complications: ["status asthmaticus", "respiratory fatigue", "silent chest", "recurrent hospital admission"],
    redFlags: ["unable to speak full sentences", "oxygen saturation below 92%", "silent chest", "drowsiness", "peak flow collapse"],
    supportiveCare: ["trigger avoidance", "inhaler technique review", "spacer use", "oxygen when hypoxic"],
    monitoring: ["oxygen saturation", "respiratory rate", "pulse", "response after bronchodilator"],
    followUp: ["review controller plan within 1 week after flare", "document action plan", "step up preventer therapy if recurrent"],
    disposition: ["discharge only when symptoms and saturation improve", "admit if repeated bronchodilators needed", "ICU if exhaustion or worsening gas exchange"],
    differentialClues: ["episodic wheeze with reversibility suggests asthma", "infective sputum or focal crackles suggests alternate diagnosis"],
    vitalPatterns: [
      { metric: "respiratoryRate", expected: "tachypnea during flare", interpretation: "increased work of breathing", highAlert: 22 },
      { metric: "oxygenSaturation", expected: "drops in moderate to severe flare", interpretation: "poor gas exchange or fatigue", lowAlert: 92 },
      { metric: "pulse", expected: "tachycardia during distress or after bronchodilator", interpretation: "severity marker", highAlert: 100 },
    ],
    investigationPlan: [
      { name: "Peak flow", type: "Other", priority: "Urgent", reason: "quantify airway obstruction at bedside", expectedFindings: "reduced compared with personal best" },
      { name: "Spirometry", type: "Other", priority: "Routine", reason: "confirm reversible obstruction outside severe acute flare", expectedFindings: "improved FEV1 after bronchodilator" },
      { name: "Chest X-ray", type: "Imaging", priority: "Targeted", reason: "exclude pneumonia or pneumothorax in atypical or severe presentation", expectedFindings: "often normal or hyperinflated" },
    ],
    treatmentPlan: [
      { category: "Rescue", medicineName: "Salbutamol", rationale: "rapid bronchodilation for acute symptoms", dose: "2 puffs", frequency: "every 4-6 hours as needed", duration: "until symptoms settle", instructions: "increase via spacer or nebulizer during acute flare per guideline", commonSideEffects: ["tremor", "tachycardia"], contraindications: [] },
      { category: "Long-term", medicineName: "Budesonide", rationale: "controller therapy to reduce airway inflammation", dose: "200 mcg", frequency: "twice daily", duration: "ongoing", instructions: "rinse mouth after use", commonSideEffects: ["oral thrush", "dysphonia"], contraindications: ["hypersensitivity"] },
      { category: "Adjunct", medicineName: "Prednisolone", rationale: "short burst for moderate or severe exacerbation", dose: "40 mg", frequency: "once daily", duration: "5 days", instructions: "use during flare requiring systemic steroids", commonSideEffects: ["hyperglycemia", "mood change"], contraindications: ["uncontrolled infection without supervision"] },
    ],
  },
  "I21.9": {
    summary: "Acute myocardial ischemia with cardiomyocyte necrosis. Rapid antiplatelet therapy, ECG interpretation, and reperfusion planning drive outcome.",
    riskFactors: ["smoker", "diabetes", "hypertension", "dyslipidemia", "family history of premature CAD"],
    complications: ["arrhythmia", "cardiogenic shock", "acute heart failure", "mechanical complications"],
    redFlags: ["hypotension", "ongoing chest pain", "ventricular arrhythmia", "pulmonary edema", "syncope"],
    supportiveCare: ["continuous monitoring", "oxygen if hypoxic", "pain control per protocol", "early reperfusion pathway"],
    monitoring: ["serial ECG", "troponin trend", "blood pressure", "heart rhythm"],
    followUp: ["cardiology review", "secondary prevention plan", "cardiac rehabilitation", "risk factor modification"],
    disposition: ["activate emergency pathway", "admit to monitored bed or coronary care", "urgent cath lab when indicated"],
    differentialClues: ["ischemic chest pain with troponin rise favors MI", "pleuritic pain or positional pain should widen the differential"],
    vitalPatterns: [
      { metric: "bloodPressureSystolic", expected: "may fall in extensive infarction", interpretation: "hypotension suggests shock or RV involvement", lowAlert: 90 },
      { metric: "pulse", expected: "tachycardia common with pain or shock", interpretation: "watch for hemodynamic compromise", highAlert: 100 },
      { metric: "oxygenSaturation", expected: "may drop with pulmonary edema", interpretation: "consider heart failure", lowAlert: 92 },
    ],
    investigationPlan: [
      { name: "ECG", type: "ECG", priority: "Urgent", reason: "identify STEMI, ischemia, or arrhythmia", expectedFindings: "ST elevation, depression, or dynamic changes" },
      { name: "Troponin", type: "Lab", priority: "Urgent", reason: "confirm myocardial injury", expectedFindings: "elevated cardiac troponin" },
      { name: "Echocardiogram", type: "Imaging", priority: "Targeted", reason: "assess wall motion and complications", expectedFindings: "regional wall motion abnormality" },
      { name: "Coronary angiography", type: "Imaging", priority: "Urgent", reason: "define culprit lesion and reperfusion strategy", expectedFindings: "occlusive coronary lesion" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Aspirin", rationale: "immediate antiplatelet therapy", dose: "300 mg loading then 75 mg", frequency: "once daily", duration: "ongoing", instructions: "give early unless contraindicated", commonSideEffects: ["GI irritation", "bleeding"], contraindications: ["active bleeding", "aspirin hypersensitivity"] },
      { category: "Adjunct", medicineName: "Clopidogrel", rationale: "dual antiplatelet therapy in ACS", dose: "300-600 mg loading then 75 mg", frequency: "once daily", duration: "as guided by ACS pathway", instructions: "combine with aspirin unless contraindicated", commonSideEffects: ["bleeding", "rash"], contraindications: ["active bleeding"] },
      { category: "Adjunct", medicineName: "Nitroglycerin", rationale: "symptom control when blood pressure tolerates", dose: "0.4 mg", frequency: "sublingual every 5 minutes up to 3 doses", duration: "acute phase", instructions: "avoid if hypotensive or phosphodiesterase inhibitor use", commonSideEffects: ["headache", "hypotension"], contraindications: ["systolic BP below 90", "recent sildenafil use"] },
      { category: "Long-term", medicineName: "Atorvastatin", rationale: "secondary prevention and plaque stabilization", dose: "40-80 mg", frequency: "once daily", duration: "ongoing", instructions: "start high intensity unless contraindicated", commonSideEffects: ["myalgia", "elevated liver enzymes"], contraindications: ["active liver disease"] },
      { category: "Long-term", medicineName: "Metoprolol", rationale: "reduce myocardial oxygen demand when appropriate", dose: "25 mg", frequency: "twice daily", duration: "ongoing", instructions: "avoid in shock, bradycardia, or acute decompensated failure", commonSideEffects: ["bradycardia", "fatigue"], contraindications: ["cardiogenic shock", "severe bradycardia"] },
      { category: "Long-term", medicineName: "Lisinopril", rationale: "ventricular remodeling benefit post-MI", dose: "5-10 mg", frequency: "once daily", duration: "ongoing", instructions: "start once hemodynamically stable", commonSideEffects: ["cough", "hyperkalemia"], contraindications: ["pregnancy", "renal artery stenosis"] },
    ],
  },
  "E11.9": {
    summary: "Chronic insulin resistance syndrome with vascular and metabolic complications driven by poor glycemic control.",
    riskFactors: ["obesity", "family history", "sedentary lifestyle", "hypertension", "dyslipidemia"],
    complications: ["retinopathy", "nephropathy", "neuropathy", "cardiovascular disease"],
    redFlags: ["marked hyperglycemia", "weight loss", "ketosis symptoms", "recurrent hypoglycemia on therapy"],
    supportiveCare: ["nutrition counseling", "exercise prescription", "foot care", "sick day education"],
    monitoring: ["fasting glucose", "HbA1c trend", "blood pressure", "weight"],
    followUp: ["quarterly glycemic review until controlled", "annual eye exam", "annual urine albumin testing", "cardiovascular risk review"],
    disposition: ["manage outpatient if stable", "escalate if severe hyperglycemia, dehydration, or ketosis"],
    differentialClues: ["gradual metabolic symptoms favor T2DM", "acute weight loss or ketosis should prompt concern for insulin deficiency"],
    vitalPatterns: [
      { metric: "bloodGlucose", expected: "persistent hyperglycemia", interpretation: "poor glycemic control", highAlert: 200 },
      { metric: "bloodPressureSystolic", expected: "hypertension often coexists", interpretation: "cardiovascular risk burden", highAlert: 140 },
    ],
    investigationPlan: [
      { name: "Fasting glucose", type: "Lab", priority: "Routine", reason: "confirm and trend glycemia", expectedFindings: "fasting hyperglycemia" },
      { name: "HbA1c", type: "Lab", priority: "Routine", reason: "assess three month glycemic control", expectedFindings: "elevated glycosylated hemoglobin" },
      { name: "Urine albumin-creatinine ratio", type: "Lab", priority: "Routine", reason: "screen nephropathy", expectedFindings: "microalbuminuria when early renal disease is present" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Metformin", rationale: "first-line insulin sensitizer", dose: "500 mg", frequency: "twice daily", duration: "ongoing", instructions: "titrate with meals as tolerated", commonSideEffects: ["nausea", "diarrhea"], contraindications: ["severe renal impairment"] },
      { category: "Adjunct", medicineName: "Insulin (Human)", rationale: "consider when control is poor or acute illness causes marked hyperglycemia", dose: "as per sliding scale", frequency: "individualized", duration: "as needed or ongoing", instructions: "pair with glucose monitoring and hypoglycemia education", commonSideEffects: ["hypoglycemia", "weight gain"], contraindications: [] },
    ],
  },
  "I10": {
    summary: "Chronic elevation in systemic arterial pressure that silently drives stroke, kidney disease, and cardiovascular remodeling.",
    riskFactors: ["obesity", "high salt diet", "chronic kidney disease", "family history", "diabetes"],
    complications: ["stroke", "heart failure", "chronic kidney disease", "retinopathy"],
    redFlags: ["severe headache with very high BP", "neurologic deficit", "chest pain", "acute pulmonary edema"],
    supportiveCare: ["salt reduction", "weight loss", "exercise", "home blood pressure logging"],
    monitoring: ["home blood pressure trend", "renal function", "potassium if on ACE inhibitor", "cardiovascular risk factors"],
    followUp: ["repeat BP review in 2-4 weeks after medication changes", "confirm adherence and lifestyle measures"],
    disposition: ["manage outpatient if uncomplicated", "send urgently if hypertensive emergency symptoms appear"],
    differentialClues: ["persistent repeated elevation confirms hypertension", "episodic anxiety alone should not be overcalled without repeated readings"],
    vitalPatterns: [
      { metric: "bloodPressureSystolic", expected: "sustained elevation", interpretation: "persistent systolic hypertension", highAlert: 140 },
      { metric: "bloodPressureDiastolic", expected: "elevated diastolic pressure may coexist", interpretation: "persistent diastolic hypertension", highAlert: 90 },
    ],
    investigationPlan: [
      { name: "Home BP monitoring", type: "Other", priority: "Routine", reason: "confirm persistent elevation outside clinic", expectedFindings: "repeated elevated readings" },
      { name: "24-hour ambulatory BP", type: "Other", priority: "Targeted", reason: "exclude white coat effect and assess burden", expectedFindings: "day-night pattern and sustained hypertension" },
      { name: "ECG", type: "ECG", priority: "Routine", reason: "screen for LVH or ischemic change", expectedFindings: "LVH or strain pattern" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Lisinopril", rationale: "useful first-line agent especially with diabetes or heart failure risk", dose: "10 mg", frequency: "once daily", duration: "ongoing", instructions: "monitor creatinine and potassium after initiation", commonSideEffects: ["dry cough", "hyperkalemia"], contraindications: ["pregnancy", "bilateral renal artery stenosis"] },
      { category: "Adjunct", medicineName: "Amlodipine", rationale: "good add-on or alternative antihypertensive", dose: "5 mg", frequency: "once daily", duration: "ongoing", instructions: "titrate to blood pressure response", commonSideEffects: ["peripheral edema", "headache"], contraindications: ["severe aortic stenosis"] },
      { category: "Long-term", medicineName: "Atorvastatin", rationale: "consider as part of cardiovascular risk reduction when indicated", dose: "10-40 mg", frequency: "once daily", duration: "ongoing", instructions: "pair with global cardiovascular risk assessment", commonSideEffects: ["myalgia", "elevated liver enzymes"], contraindications: ["active liver disease"] },
    ],
  },
  A09: {
    summary: "Acute infectious gastrointestinal syndrome with volume loss, electrolyte disturbance, and usually self-limited disease.",
    riskFactors: ["contaminated food exposure", "travel history", "young or older age", "immunocompromised state"],
    complications: ["dehydration", "acute kidney injury", "electrolyte imbalance", "sepsis in vulnerable patients"],
    redFlags: ["hypotension", "persistent vomiting", "bloody diarrhea", "reduced urine output", "mental status change"],
    supportiveCare: ["aggressive oral rehydration", "electrolyte replacement", "infection control hygiene", "light diet as tolerated"],
    monitoring: ["fluid balance", "pulse", "blood pressure", "temperature"],
    followUp: ["review if not improving within 48 hours", "escalate if blood in stool or severe dehydration"],
    disposition: ["outpatient when tolerating fluids", "admit if shock, AKI, or inability to hydrate"],
    differentialClues: ["vomiting and diarrhea after exposure suggests gastroenteritis", "localized peritonism should trigger surgical reconsideration"],
    vitalPatterns: [
      { metric: "pulse", expected: "tachycardia from dehydration", interpretation: "volume depletion", highAlert: 100 },
      { metric: "bloodPressureSystolic", expected: "may fall when dehydration is severe", interpretation: "hemodynamic compromise", lowAlert: 90 },
      { metric: "temperature", expected: "fever may occur with infection", interpretation: "infective burden", highAlert: 38 },
    ],
    investigationPlan: [
      { name: "Electrolytes", type: "Lab", priority: "Routine", reason: "evaluate dehydration and potassium derangement", expectedFindings: "electrolyte imbalance in moderate or severe disease" },
      { name: "CBC", type: "Lab", priority: "Routine", reason: "screen inflammatory response and hemoconcentration", expectedFindings: "hemoconcentration or leukocytosis" },
      { name: "Stool culture", type: "Lab", priority: "Targeted", reason: "identify invasive bacterial cause when severe or prolonged", expectedFindings: "pathogen identification" },
    ],
    treatmentPlan: [
      { category: "Supportive", medicineName: "Ondansetron", rationale: "control vomiting to allow oral rehydration", dose: "4 mg", frequency: "every 8 hours as needed", duration: "1-3 days", instructions: "reserve for troublesome vomiting", commonSideEffects: ["constipation", "QT prolongation"], contraindications: ["significant QT prolongation"] },
    ],
  },
  K37: {
    summary: "Progressive appendiceal inflammation where perforation risk rises with delay. Surgical review is the key management step.",
    riskFactors: ["adolescent or young adult age", "migration of pain to right iliac fossa", "anorexia", "fever"],
    complications: ["perforation", "appendiceal abscess", "peritonitis", "sepsis"],
    redFlags: ["generalized guarding", "hemodynamic instability", "worsening sepsis", "rigid abdomen"],
    supportiveCare: ["nil by mouth", "IV fluids", "analgesia", "early surgical consultation"],
    monitoring: ["pain migration", "temperature", "heart rate", "abdominal signs"],
    followUp: ["postoperative review", "watch for wound infection or abscess"],
    disposition: ["urgent surgical pathway", "admit for observation or operation"],
    differentialClues: ["McBurney tenderness and migratory pain favor appendicitis", "diffuse diarrhea-predominant illness suggests gastroenteritis instead"],
    vitalPatterns: [
      { metric: "temperature", expected: "low grade fever is common", interpretation: "higher fever suggests perforation or sepsis", highAlert: 38 },
      { metric: "pulse", expected: "tachycardia may reflect pain or perforation", interpretation: "watch for sepsis", highAlert: 100 },
    ],
    investigationPlan: [
      { name: "CBC", type: "Lab", priority: "Routine", reason: "support inflammatory diagnosis", expectedFindings: "neutrophilic leukocytosis" },
      { name: "Ultrasound", type: "Imaging", priority: "Routine", reason: "useful in children or pregnancy", expectedFindings: "non-compressible inflamed appendix" },
      { name: "CT abdomen/pelvis", type: "Imaging", priority: "Targeted", reason: "clarify diagnosis when examination is equivocal", expectedFindings: "dilated inflamed appendix with periappendiceal fat stranding" },
    ],
    treatmentPlan: [
      { category: "Adjunct", medicineName: "Ceftriaxone", rationale: "perioperative or preoperative antibiotic coverage", dose: "1-2 g", frequency: "once daily", duration: "as perioperative course", instructions: "follow local surgical antimicrobial policy", commonSideEffects: ["diarrhea", "biliary sludge"], contraindications: ["severe cephalosporin allergy"] },
    ],
  },
  "I50.9": {
    summary: "Clinical syndrome of congestion and reduced cardiac reserve requiring diuresis, afterload reduction, and careful volume monitoring.",
    riskFactors: ["ischemic heart disease", "longstanding hypertension", "cardiomyopathy", "valvular disease", "diabetes"],
    complications: ["acute pulmonary edema", "renal dysfunction", "arrhythmia", "cardiogenic shock"],
    redFlags: ["rest dyspnea", "oxygen saturation below 92%", "hypotension", "rapid weight gain", "new confusion"],
    supportiveCare: ["salt restriction", "daily weights", "fluid balance review", "oxygen when hypoxic"],
    monitoring: ["blood pressure", "pulse", "oxygen saturation", "weight and edema"],
    followUp: ["heart failure clinic review", "renal function after medication changes", "medication titration plan"],
    disposition: ["admit when decompensated or hypoxic", "outpatient follow-up only if clinically stable"],
    differentialClues: ["orthopnea and edema with elevated JVP favor heart failure", "isolated wheeze should still consider asthma or COPD"],
    vitalPatterns: [
      { metric: "oxygenSaturation", expected: "falls during pulmonary edema", interpretation: "decompensation marker", lowAlert: 92 },
      { metric: "pulse", expected: "tachycardia often accompanies low output states", interpretation: "compensatory response", highAlert: 100 },
      { metric: "bloodPressureSystolic", expected: "may be low in advanced failure", interpretation: "poor perfusion risk", lowAlert: 90 },
    ],
    investigationPlan: [
      { name: "Echocardiogram", type: "Imaging", priority: "Routine", reason: "define systolic and structural disease", expectedFindings: "reduced EF or structural abnormality" },
      { name: "BNP", type: "Lab", priority: "Routine", reason: "support diagnosis in dyspnea", expectedFindings: "elevated natriuretic peptide" },
      { name: "Chest X-ray", type: "Imaging", priority: "Routine", reason: "look for congestion and cardiomegaly", expectedFindings: "pulmonary edema or pleural effusion" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Furosemide", rationale: "relieve congestion in fluid overloaded patients", dose: "40 mg", frequency: "once or twice daily", duration: "titrate to congestion", instructions: "monitor renal function and potassium", commonSideEffects: ["hypokalemia", "dehydration"], contraindications: ["severe dehydration"] },
      { category: "Long-term", medicineName: "Lisinopril", rationale: "afterload reduction and remodeling benefit", dose: "5-10 mg", frequency: "once daily", duration: "ongoing", instructions: "check creatinine and potassium after starting", commonSideEffects: ["cough", "hyperkalemia"], contraindications: ["pregnancy", "renal artery stenosis"] },
      { category: "Long-term", medicineName: "Metoprolol", rationale: "beta blockade improves long-term outcomes when stable", dose: "12.5-25 mg", frequency: "twice daily", duration: "ongoing", instructions: "start only once euvolemic and stable", commonSideEffects: ["bradycardia", "fatigue"], contraindications: ["acute cardiogenic shock"] },
    ],
  },
  "N39.0": {
    summary: "Bacterial urinary infection ranging from cystitis to complicated infection. Pattern recognition and targeted antibiotics are central.",
    riskFactors: ["female sex", "recent sexual activity", "urinary catheter", "diabetes", "urinary obstruction"],
    complications: ["pyelonephritis", "urosepsis", "recurrent infection", "renal involvement"],
    redFlags: ["fever with flank pain", "hypotension", "confusion", "pregnancy", "male patient with severe symptoms"],
    supportiveCare: ["oral hydration", "analgesia", "review culture results", "screen for complicated features"],
    monitoring: ["temperature", "symptom improvement", "hydration", "culture-directed response"],
    followUp: ["review if no improvement in 48 hours", "address recurrent infection triggers"],
    disposition: ["outpatient for uncomplicated cystitis", "admit if septic, pregnant with severe infection, or obstructed"],
    differentialClues: ["dysuria with frequency favors UTI", "vaginal symptoms or renal colic should broaden the differential"],
    vitalPatterns: [
      { metric: "temperature", expected: "fever suggests ascending or systemic infection", interpretation: "concern for pyelonephritis or sepsis", highAlert: 37.8 },
      { metric: "pulse", expected: "tachycardia may occur when systemically unwell", interpretation: "more severe infection", highAlert: 100 },
    ],
    investigationPlan: [
      { name: "Urinalysis", type: "Lab", priority: "Routine", reason: "screen for pyuria and nitrites", expectedFindings: "leukocytes, nitrites, microscopic blood" },
      { name: "Urine culture", type: "Lab", priority: "Routine", reason: "confirm organism and sensitivity", expectedFindings: "significant bacteriuria" },
      { name: "Ultrasound", type: "Imaging", priority: "Targeted", reason: "look for obstruction or complicated disease", expectedFindings: "hydronephrosis or structural issue when complicated" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Nitrofurantoin", rationale: "typical first-line option for uncomplicated lower UTI", dose: "100 mg", frequency: "twice daily", duration: "5 days", instructions: "avoid in severe renal impairment", commonSideEffects: ["nausea", "dark urine"], contraindications: ["significant renal impairment"] },
      { category: "Adjunct", medicineName: "Amoxicillin", rationale: "alternative only when culture supports susceptibility", dose: "500 mg", frequency: "three times daily", duration: "5-7 days", instructions: "do not use empirically where resistance is high", commonSideEffects: ["diarrhea", "rash"], contraindications: ["penicillin allergy"] },
    ],
  },
  "A41.9": {
    summary: "Dysregulated host response to infection with organ dysfunction risk. Antibiotics, cultures, fluids, and source control are time critical.",
    riskFactors: ["immunocompromised state", "indwelling devices", "recent hospitalization", "elderly age", "diabetes"],
    complications: ["septic shock", "AKI", "ARDS", "multiorgan failure"],
    redFlags: ["systolic blood pressure below 90", "altered mental status", "lactate elevation", "oliguria", "hypoxia"],
    supportiveCare: ["early IV fluids", "oxygen support", "strict urine output charting", "source control planning"],
    monitoring: ["blood pressure", "pulse", "respiratory rate", "oxygen saturation", "urine output"],
    followUp: ["daily review of cultures and de-escalation", "reassess source control", "monitor for organ failure"],
    disposition: ["urgent admission", "ICU escalation if shock or organ dysfunction"],
    differentialClues: ["infection plus hypotension or delirium should trigger sepsis thinking", "tachycardia alone without infection is insufficient"],
    vitalPatterns: [
      { metric: "temperature", expected: "fever or hypothermia", interpretation: "systemic inflammatory dysregulation", highAlert: 38, lowAlert: 36 },
      { metric: "pulse", expected: "tachycardia is common", interpretation: "circulatory stress", highAlert: 90 },
      { metric: "respiratoryRate", expected: "tachypnea is common", interpretation: "early severity marker", highAlert: 22 },
      { metric: "bloodPressureSystolic", expected: "can fall with vasodilation or shock", interpretation: "poor perfusion", lowAlert: 90 },
    ],
    investigationPlan: [
      { name: "Blood cultures", type: "Lab", priority: "Urgent", reason: "identify bloodstream infection", expectedFindings: "pathogen growth before antibiotics where feasible" },
      { name: "CBC", type: "Lab", priority: "Urgent", reason: "assess inflammatory response and cytopenia", expectedFindings: "leukocytosis, leukopenia, or thrombocytopenia" },
      { name: "Lactate", type: "Lab", priority: "Urgent", reason: "risk stratify tissue hypoperfusion", expectedFindings: "elevated lactate in shock or poor perfusion" },
      { name: "Chest X-ray", type: "Imaging", priority: "Targeted", reason: "common search for pulmonary source", expectedFindings: "source dependent abnormality" },
    ],
    treatmentPlan: [
      { category: "First-line", medicineName: "Ceftriaxone", rationale: "broad empiric option while source is clarified in some pathways", dose: "2 g", frequency: "once daily", duration: "source dependent", instructions: "tailor to likely source and local antibiogram", commonSideEffects: ["diarrhea", "biliary sludge"], contraindications: ["severe cephalosporin allergy"] },
    ],
  },
  "J93.9": {
    summary: "Air in the pleural space causing loss of lung expansion. Management is driven by size, symptoms, and respiratory compromise.",
    riskFactors: ["tall thin habitus", "smoker", "underlying lung disease", "trauma", "positive pressure ventilation"],
    complications: ["tension pneumothorax", "respiratory failure", "recurrence", "hemodynamic collapse"],
    redFlags: ["severe hypoxia", "hypotension", "tracheal deviation", "rapid respiratory distress"],
    supportiveCare: ["high flow oxygen when indicated", "urgent decompression if tension suspected", "repeat imaging"],
    monitoring: ["oxygen saturation", "respiratory rate", "hemodynamics", "repeat chest imaging"],
    followUp: ["pulmonary review after discharge", "smoking cessation advice", "repeat imaging to confirm resolution"],
    disposition: ["observe small stable cases", "admit symptomatic or secondary cases", "emergency intervention if tension physiology"],
    differentialClues: ["sudden pleuritic pain and unilateral breath sound loss favor pneumothorax", "fever and crackles suggest infection instead"],
    vitalPatterns: [
      { metric: "oxygenSaturation", expected: "may fall if lung collapse is significant", interpretation: "severity marker", lowAlert: 92 },
      { metric: "respiratoryRate", expected: "tachypnea during respiratory distress", interpretation: "increased work of breathing", highAlert: 22 },
      { metric: "pulse", expected: "tachycardia in pain or tension physiology", interpretation: "hemodynamic strain", highAlert: 100 },
    ],
    investigationPlan: [
      { name: "Chest X-ray", type: "Imaging", priority: "Urgent", reason: "confirm presence and size of pneumothorax", expectedFindings: "visible pleural line and absent peripheral lung markings" },
      { name: "CT chest", type: "Imaging", priority: "Targeted", reason: "define underlying disease or uncertain anatomy", expectedFindings: "small occult pneumothorax or bullous disease" },
    ],
    treatmentPlan: [],
  },
};
