import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // Seed Specialties
  const specialties = [
    { name: "General Medicine", description: "Internal medicine" },
    { name: "Pediatrics", description: "Child and adolescent medicine" },
    { name: "Cardiology", description: "Heart and cardiovascular system" },
    { name: "Dermatology", description: "Skin conditions" },
    { name: "Neurology", description: "Nervous system disorders" },
  ];

  for (const s of specialties) {
    await prisma.specialty.upsert({
      where: { name: s.name },
      update: s,
      create: s,
    });
  }

  // Seed Diseases
  const diseases = [
    {
      name: "Hypertension",
      icdCode: "I10",
      specialty: "General Medicine",
      definition: "Persistently elevated blood pressure",
      pathophysiology: "Increased peripheral resistance",
      epidemiology: "Affects 1 in 3 adults",
      symptoms: ["headache", "dizziness", "blurred vision"],
      signs: ["elevated blood pressure", "retinopathy"],
      diagnosticCriteria: ["BP ≥140/90 on 3 separate occasions"],
      investigations: ["CBC", "lipid profile", "renal function", "ECG"],
      management: "Lifestyle modification, ACE inhibitors, thiazide diuretics",
      prognosis: "Good with treatment",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Type 2 Diabetes Mellitus",
      icdCode: "E11",
      specialty: "General Medicine",
      definition: "Chronic hyperglycemia due to insulin resistance",
      pathophysiology: "Insulin resistance with relative insulin deficiency",
      epidemiology: "Affects 10% of adults globally",
      symptoms: ["polyuria", "polydipsia", "weight loss", "fatigue"],
      signs: ["elevated blood glucose", "glycosuria"],
      diagnosticCriteria: ["Fasting glucose ≥126 mg/dL", "HbA1c ≥6.5%"],
      investigations: ["FBS", "PPBS", "HbA1c", "lipid profile"],
      management: "Metformin, diet control, exercise",
      prognosis: "Good with glycemic control",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Acute Myocardial Infarction",
      icdCode: "I21",
      specialty: "Cardiology",
      definition: "Necrosis of myocardial tissue due to prolonged ischemia",
      pathophysiology: "Coronary artery occlusion leading to myocardial necrosis",
      epidemiology: "Leading cause of death worldwide",
      symptoms: ["chest pain", "dyspnea", "diaphoresis", "nausea"],
      signs: ["elevated cardiac enzymes", "ST elevation", "new Q waves"],
      diagnosticCriteria: ["Rise and fall of troponin", "ECG changes", "Symptoms"],
      investigations: ["ECG", "troponin", "CK-MB", "echocardiogram"],
      management: "Reperfusion therapy, beta-blockers, ACE inhibitors, statins",
      prognosis: "Depends on extent and timely reperfusion",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Asthma",
      icdCode: "J45",
      specialty: "General Medicine",
      definition: "Chronic inflammatory disorder of airways",
      pathophysiology: "Airway hyperresponsiveness and inflammation",
      epidemiology: "Affects 300 million worldwide",
      symptoms: ["wheezing", "cough", "dyspnea", "chest tightness"],
      signs: ["expiratory wheezes", "prolonged expiration"],
      diagnosticCriteria: ["Variable expiratory airflow limitation", "Reversibility with bronchodilators"],
      investigations: ["spirometry", "peak expiratory flow", "chest X-ray"],
      management: "Inhaled corticosteroids, SABA, LABA",
      prognosis: "Good with proper control",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Pneumonia",
      icdCode: "J15",
      specialty: "General Medicine",
      definition: "Infection of lung parenchyma",
      pathophysiology: "Inflammatory response to infection in alveoli",
      epidemiology: "Common cause of morbidity worldwide",
      symptoms: ["fever", "cough", "sputum production", "dyspnea"],
      signs: ["fever", "tachypnea", "rales", "dullness to percussion"],
      diagnosticCriteria: ["New infiltrate on CXR", "Fever", "Cough", "Sputum"],
      investigations: ["CXR", "CBC", "sputum culture", "blood culture"],
      management: "Appropriate antibiotics, supportive care",
      prognosis: "Good with appropriate antibiotics",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Migraine",
      icdCode: "G43",
      specialty: "Neurology",
      definition: "Recurrent moderate to severe headache disorder",
      pathophysiology: "Abnormal neuronal excitability and vascular changes",
      epidemiology: "Affects 15% of population",
      symptoms: ["unilateral headache", "nausea", "photophobia", "phonophobia"],
      signs: ["normal neurological examination", " scalp tenderness"],
      diagnosticCriteria: ["5+ attacks lasting 4-72h", "Unilateral, pulsating, moderate-severe", "Nausea/vomiting, photophobia"],
      investigations: ["Clinical diagnosis", "MRI brain if atypical"],
      management: "Acute: triptans, NSAIDs. Prophylaxis: beta-blockers, antidepressants",
      prognosis: "Chronic but manageable",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Atopic Dermatitis",
      icdCode: "L20",
      specialty: "Dermatology",
      definition: "Chronic relapsing inflammatory skin disorder",
      pathophysiology: "Skin barrier dysfunction with type 2 inflammation",
      epidemiology: "Affects 15-30% of children, 2-10% of adults",
      symptoms: ["itching", "dry skin", "rash"],
      signs: ["eczema", "lichenification", "xerosis"],
      diagnosticCriteria: ["Pruritus", "Typical morphology and distribution", "Chronic or relapsing course"],
      investigations: ["Clinical diagnosis", "Skin prick testing"],
      management: "Emollients, topical corticosteroids, calcineurin inhibitors",
      prognosis: "Often improves with age in children",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Heart Failure",
      icdCode: "I50",
      specialty: "Cardiology",
      definition: "Inability of the heart to pump blood at a rate sufficient to meet metabolic demands",
      pathophysiology: "Reduced cardiac output leading to systemic and pulmonary congestion",
      epidemiology: "Affects 2% of adult population",
      symptoms: ["dyspnea", "orthopnea", "fatigue", "ankle swelling"],
      signs: ["elevated JVP", "displaced apex beat", "crackles in lungs"],
      diagnosticCriteria: ["Framingham criteria", "Echocardiographic evidence"],
      investigations: ["NT-proBNP", "Echocardiogram", "ECG", "CXR"],
      management: "ACE inhibitors, beta-blockers, diuretics",
      prognosis: "Variable, requires long-term management",
      reference: "Oxford Textbook of Medicine",
    },
    {
      name: "Chronic Obstructive Pulmonary Disease",
      icdCode: "J44",
      specialty: "Pulmonology",
      definition: "Persistent respiratory symptoms and airflow limitation",
      pathophysiology: "Chronic inflammation of the airways and lung parenchyma",
      epidemiology: "Commonly associated with smoking",
      symptoms: ["chronic cough", "sputum production", "dyspnea"],
      signs: ["wheezing", "pursed-lip breathing", "use of accessory muscles"],
      diagnosticCriteria: ["FEV1/FVC < 0.70 post-bronchodilator"],
      investigations: ["Spirometry", "CXR", "ABG"],
      management: "Smoking cessation, bronchodilators, oxygen therapy",
      prognosis: "Progressive, management improves quality of life",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Peptic Ulcer Disease",
      icdCode: "K27",
      specialty: "Gastroenterology",
      definition: "Ulceration in the stomach or duodenum",
      pathophysiology: "Imbalance between aggressive and defensive factors in the gastric mucosa",
      epidemiology: "Often associated with H. pylori or NSAID use",
      symptoms: ["epigastric pain", "bloating", "nausea", "heartburn"],
      signs: ["epigastric tenderness", "signs of anemia if bleeding"],
      diagnosticCriteria: ["Endoscopic confirmation"],
      investigations: ["Upper GI Endoscopy", "H. pylori test"],
      management: "PPIs, H. pylori eradication therapy",
      prognosis: "Good with treatment",
      reference: "Kumar & Clark's Clinical Medicine",
    },
    {
      name: "Urinary Tract Infection",
      icdCode: "N39",
      specialty: "Nephrology",
      definition: "Infection of any part of the urinary system",
      pathophysiology: "Bacterial colonization of the urinary tract",
      epidemiology: "More common in females",
      symptoms: ["dysuria", "frequency", "urgency", "suprapubic pain"],
      signs: ["fever", "suprapubic tenderness"],
      diagnosticCriteria: ["Significant bacteriuria in urine culture"],
      investigations: ["Urinalysis", "Urine culture", "Ultrasound if recurrent"],
      management: "Antibiotics, hydration",
      prognosis: "Excellent with treatment",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Parkinson's Disease",
      icdCode: "G20",
      specialty: "Neurology",
      definition: "Progressive neurodegenerative disorder affecting movement",
      pathophysiology: "Loss of dopaminergic neurons in the substantia nigra",
      epidemiology: "Commonly affects older adults",
      symptoms: ["tremor", "rigidity", "bradykinesia", "postural instability"],
      signs: ["resting tremor", "cogwheel rigidity", "shuffling gait"],
      diagnosticCriteria: ["Clinical diagnosis based on motor symptoms"],
      investigations: ["Clinical assessment", "MRI to rule out other causes"],
      management: "Levodopa, dopamine agonists, physical therapy",
      prognosis: "Chronic progressive condition",
      reference: "Oxford Textbook of Medicine",
    },
    {
      name: "Hyperthyroidism",
      icdCode: "E05",
      specialty: "Endocrinology",
      definition: "Overactive thyroid gland leading to excessive thyroid hormone",
      pathophysiology: "Increased synthesis and secretion of thyroid hormones",
      epidemiology: "More common in females",
      symptoms: ["weight loss", "tachycardia", "heat intolerance", "tremor"],
      signs: ["goiter", "exophthalmos", "tachycardia", "moist skin"],
      diagnosticCriteria: ["Low TSH, elevated free T4/T3"],
      investigations: ["Thyroid function tests", "Radioactive iodine uptake"],
      management: "Anti-thyroid drugs, radioactive iodine, surgery",
      prognosis: "Good with management",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Rheumatoid Arthritis",
      icdCode: "M05",
      specialty: "Rheumatology",
      definition: "Chronic autoimmune inflammatory joint disease",
      pathophysiology: "Systemic autoimmune process leading to synovial inflammation",
      epidemiology: "Affects 1% of population",
      symptoms: ["joint pain", "morning stiffness", "fatigue", "swelling"],
      signs: ["symmetrical joint swelling", "joint deformities", "nodules"],
      diagnosticCriteria: ["ACR/EULAR criteria"],
      investigations: ["RF", "anti-CCP", "ESR", "CRP", "X-ray"],
      management: "DMARDs, NSAIDs, corticosteroids",
      prognosis: "Variable, early treatment improves outcome",
      reference: "Harrison's Principles of Internal Medicine",
    },
    {
      name: "Tuberculosis",
      icdCode: "A15",
      specialty: "Infectious Diseases",
      definition: "Infectious disease caused by Mycobacterium tuberculosis",
      pathophysiology: "Granulomatous inflammation primarily in the lungs",
      epidemiology: "Significant global health burden",
      symptoms: ["chronic cough", "fever", "night sweats", "weight loss"],
      signs: ["fever", "lymphadenopathy", "crackles in lungs"],
      diagnosticCriteria: ["Sputum AFB positive", "GeneXpert positive", "CXR findings"],
      investigations: ["Sputum microscopy", "Culture", "CXR", "IGRA"],
      management: "Anti-TB drugs (RIPE) for 6-9 months",
      prognosis: "Good if treatment completed",
      reference: "WHO Guidelines",
    },
    {
      name: "Cholelithiasis",
      icdCode: "K80",
      specialty: "Surgery",
      definition: "Presence of stones in the gallbladder",
      pathophysiology: "Imbalance in bile composition leading to stone formation",
      epidemiology: "Common in middle-aged females",
      symptoms: ["biliary colic", "nausea", "vomiting", "bloating"],
      signs: ["Murphy's sign if cholecystitis", "epigastric tenderness"],
      diagnosticCriteria: ["Ultrasound visualization of stones"],
      investigations: ["Abdominal ultrasound", "LFTs"],
      management: "Cholecystectomy if symptomatic, observation",
      prognosis: "Excellent with surgery",
      reference: "Sabiston Textbook of Surgery",
    },
  ];

  for (const d of diseases) {
    await prisma.disease.upsert({
      where: { icdCode: d.icdCode },
      update: d,
      create: d,
    });
  }

  // Seed Medicines
  const medicines = [
    { name: "Metformin", type: "Oral antidiabetic", uses: ["Type 2 diabetes"], dosage: "500-2000mg daily", sideEffects: ["nausea", "diarrhea"], contraindications: ["severe renal impairment"] },
    { name: "Lisinopril", type: "ACE inhibitor", uses: ["Hypertension", "Heart failure"], dosage: "10-40mg once daily", sideEffects: ["dry cough", "hyperkalemia"], contraindications: ["pregnancy", "bilateral renal artery stenosis"] },
    { name: "Amlodipine", type: "Calcium channel blocker", uses: ["Hypertension", "Angina"], dosage: "5-10mg once daily", sideEffects: ["peripheral edema", "headache"], contraindications: ["severe aortic stenosis"] },
    { name: "Salbutamol", type: "SABA", uses: ["Asthma", "COPD"], dosage: "2 puffs as needed", sideEffects: ["tremor", "tachycardia"], contraindications: [] },
    { name: "Atorvastatin", type: "Statin", uses: ["Hyperlipidemia", "CVD prevention"], dosage: "10-80mg once daily", sideEffects: ["myalgia", "elevated LFTs"], contraindications: ["active liver disease"] },
    { name: "Aspirin", type: "Antiplatelet", uses: ["CVD prevention", "Pain"], dosage: "75-325mg daily", sideEffects: ["GI bleeding", "tinnitus"], contraindications: ["active peptic ulcer", "bleeding disorders"] },
    { name: "Sumatriptan", type: "Triptan", uses: ["Migraine"], dosage: "50-100mg as needed", sideEffects: ["chest tightness", "dizziness"], contraindications: ["ischemic heart disease", "uncontrolled hypertension"] },
    { name: "Hydrocortisone cream", type: "Topical steroid", uses: ["Atopic dermatitis", "Eczema"], dosage: "Apply thin layer BID-TID", sideEffects: ["skin thinning", "hypopigmentation"], contraindications: ["fungal skin infections"] },
    { name: "Amoxicillin", type: "Penicillin antibiotic", uses: ["Pneumonia", "Infections"], dosage: "500mg TID for 7 days", sideEffects: ["diarrhea", "rash"], contraindications: ["penicillin allergy"] },
    { name: "Insulin (Human)", type: "Insulin", uses: ["Type 1 diabetes", "Type 2 diabetes"], dosage: "As per sliding scale", sideEffects: ["hypoglycemia", "weight gain"], contraindications: [] },
  ];

  for (const m of medicines) {
    await prisma.medicine.upsert({
      where: { name: m.name },
      update: m,
      create: m,
    });
  }

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
